import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from 'react';

export type Lang = 'ar' | 'en' | 'fr' | 'ber';

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Lang, Record<string, string>> = {
  ar: {
    'nav.home': 'الرئيسية',
    'nav.destinations': 'الوجهات',
    'nav.activities': 'الأنشطة',
    'nav.about': 'عن أزيلال',
    'nav.contact': 'تواصل معنا',
    'hero.badge': 'وجهتك التالية في المغرب',
    'hero.title': 'اكتشف سحر أزيلال',
    'hero.subtitle': 'بين جبال الأطلس الشاهقة والوديان الخضراء، اكتشف جمال الطبيعة وثقافة الأمازيغ الأصيلة',
    'hero.cta': 'ابدأ رحلتك',
    'featured.title': 'أبرز الوجهات',
    'featured.subtitle': 'استكشف أجمل الأماكن في إقليم أزيلال',
    'featured.1.title': 'بحيرة بين الويدان',
    'featured.1.desc': 'بحيرة ساحرة محاطة بجبال الأطلس الشاهقة، مثالية للرياضات المائية والتخييم',
    'featured.1.badge': 'مميز',
    'featured.2.title': 'شلالات تيسنيرت',
    'featured.2.desc': 'شلالات خلابة تنحدر من صخور الحمرة وسط غابات الأرز',
    'featured.2.badge': 'طبيعة',
    'featured.3.title': 'قرى أيت بومهدى',
    'featured.3.desc': 'قرى أمازيغية تقليدية تحافظ على التراث الثقافي والتقاليد العريقة',
    'featured.3.badge': 'ثقافة',
    'stats.visitors': 'زائر سنوياً',
    'stats.trails': 'مسار طبيعي',
    'stats.heritage': 'موقع تراثي',
    'stats.hospitality': 'مكان إقامة',
    'destinations.title': 'وجهات سياحية',
    'destinations.subtitle': 'اكتشف جمال أزيلال المتنوع',
    'destinations.view': 'عرض التفاصيل',
    'categories.title': 'أنواع السياحة',
    'categories.subtitle': 'اختر نوع المغامرة المناسبة لك',
    'cat.nature': 'السياحة الطبيعية',
    'cat.nature.count': '12 وجهة',
    'cat.adventure': 'المغامرات',
    'cat.adventure.count': '8 نشاطات',
    'cat.culture': 'السياحة الثقافية',
    'cat.culture.count': '6 مواقع',
    'cat.sports': 'الرياضات الجبلية',
    'cat.sports.count': '5 أنشطة',
    'map.title': 'موقع أزيلال',
    'map.desc': 'تقع أزيلال في قلب جبال الأطلس الكبير، على بعد 220 كم جنوب شرق الدار البيضاء، وتتميز بتنوع طبيعي وثقافي فريد',
    'map.f1.title': 'طبيعة خلابة',
    'map.f1.desc': 'جبال ووديان وغابات متنوعة',
    'map.f2.title': 'تراث أمازيغي',
    'map.f2.desc': 'قرى تقليدية وثقافة عريقة',
    'map.f3.title': 'مناخ معتدل',
    'map.f3.desc': 'مثالية للزيارة طوال السنة',
    'footer.about': 'السياحة في أزيلال هي بوابتك لاكتشاف أجمل ما تقدمه منطقة أزيلال من طبيعة خلابة وثقافة أمازيغية أصيلة',
    'footer.links': 'روابط سريعة',
    'footer.contact': 'معلومات التواصل',
    'footer.follow': 'تابعنا',
    'footer.copyright': 'جميع الحقوق محفوظة',
    'chat.title': 'تواصل معنا',
    'chat.subtitle': 'نحن هنا لمساعدتك في التخطيط لرحلتك',
    'chat.placeholder': 'اكتب رسالتك هنا...',
    'chat.send': 'إرسال',
    'chat.welcome': 'مرحباً! كيف يمكنني مساعدتك في التخطيط لرحلتك إلى أزيلال؟',
    'footer.newsletter': 'النشرة البريدية',
    'footer.newsletter.desc': 'اشترك لتصلك أحدث العروض والأخبار',
    'footer.email': 'بريدك الإلكتروني',
    'footer.subscribe': 'اشترك',
  },
  en: {
    'nav.home': 'Home',
    'nav.destinations': 'Destinations',
    'nav.activities': 'Activities',
    'nav.about': 'About Azilal',
    'nav.contact': 'Contact Us',
    'hero.badge': 'Your next destination in Morocco',
    'hero.title': 'Discover the Magic of Azilal',
    'hero.subtitle': 'Between towering Atlas Mountains and lush green valleys, discover the beauty of nature and authentic Amazigh culture',
    'hero.cta': 'Start Your Journey',
    'featured.title': 'Top Destinations',
    'featured.subtitle': 'Explore the most beautiful places in Azilal region',
    'featured.1.title': 'Bin el Ouidane Lake',
    'featured.1.desc': 'A magical lake surrounded by towering Atlas Mountains, perfect for water sports and camping',
    'featured.1.badge': 'Featured',
    'featured.2.title': 'Tisnirt Waterfalls',
    'featured.2.desc': 'Stunning waterfalls cascading from red sandstone cliffs amid cedar forests',
    'featured.2.badge': 'Nature',
    'featured.3.title': 'Ait Bouhaddou Villages',
    'featured.3.desc': 'Traditional Amazigh villages preserving rich cultural heritage and ancient traditions',
    'featured.3.badge': 'Culture',
    'stats.visitors': 'Visitors Annually',
    'stats.trails': 'Nature Trails',
    'stats.heritage': 'Heritage Sites',
    'stats.hospitality': 'Accommodations',
    'destinations.title': 'Tourist Destinations',
    'destinations.subtitle': 'Discover the diverse beauty of Azilal',
    'destinations.view': 'View Details',
    'categories.title': 'Types of Tourism',
    'categories.subtitle': 'Choose the adventure that suits you',
    'cat.nature': 'Nature Tourism',
    'cat.nature.count': '12 destinations',
    'cat.adventure': 'Adventures',
    'cat.adventure.count': '8 activities',
    'cat.culture': 'Cultural Tourism',
    'cat.culture.count': '6 sites',
    'cat.sports': 'Mountain Sports',
    'cat.sports.count': '5 activities',
    'map.title': 'Location of Azilal',
    'map.desc': 'Located in the heart of the High Atlas Mountains, 220 km southeast of Casablanca, Azilal features unique natural and cultural diversity',
    'map.f1.title': 'Stunning Nature',
    'map.f1.desc': 'Mountains, valleys, and diverse forests',
    'map.f2.title': 'Amazigh Heritage',
    'map.f2.desc': 'Traditional villages and rich culture',
    'map.f3.title': 'Mild Climate',
    'map.f3.desc': 'Perfect for visiting year-round',
    'footer.about': 'Azilal Tourism is your gateway to discovering the most beautiful natural landscapes and authentic Amazigh culture of the Azilal region',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact Information',
    'footer.follow': 'Follow Us',
    'footer.copyright': 'All rights reserved',
    'chat.title': 'Contact Us',
    'chat.subtitle': 'We are here to help you plan your trip',
    'chat.placeholder': 'Type your message here...',
    'chat.send': 'Send',
    'chat.welcome': 'Hello! How can I help you plan your trip to Azilal?',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Subscribe to get the latest offers and news',
    'footer.email': 'Your email',
    'footer.subscribe': 'Subscribe',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.destinations': 'Destinations',
    'nav.activities': 'Activités',
    'nav.about': 'À propos',
    'nav.contact': 'Contactez-nous',
    'hero.badge': 'Votre prochaine destination au Maroc',
    'hero.title': 'Découvrez la Magie d\'Azilal',
    'hero.subtitle': 'Entre les montagnes majestueuses de l\'Atlas et les vallées verdoyantes, découvrez la beauté de la nature et la culture amazighe authentique',
    'hero.cta': 'Commencez votre voyage',
    'featured.title': 'Destinations Phares',
    'featured.subtitle': 'Explorez les plus beaux endroits de la région d\'Azilal',
    'featured.1.title': 'Lac de Bin el Ouidane',
    'featured.1.desc': 'Un lac magique entouré par les montagnes de l\'Atlas, idéal pour les sports nautiques et le camping',
    'featured.1.badge': 'Vedette',
    'featured.2.title': 'Cascades de Tisnirt',
    'featured.2.desc': 'Des cascades spectaculaires tombant des falaises de grès rouge parmi les forêts de cèdres',
    'featured.2.badge': 'Nature',
    'featured.3.title': 'Villages d\'Ait Bouhaddou',
    'featured.3.desc': 'Des villages amazighs traditionnels préservant un riche patrimoine culturel et des traditions anciennes',
    'featured.3.badge': 'Culture',
    'stats.visitors': 'Visiteurs par an',
    'stats.trails': 'Sentiers naturels',
    'stats.heritage': 'Sites patrimoniaux',
    'stats.hospitality': 'Hébergements',
    'destinations.title': 'Destinations Touristiques',
    'destinations.subtitle': 'Découvrez la beauté diversifiée d\'Azilal',
    'destinations.view': 'Voir les détails',
    'categories.title': 'Types de Tourisme',
    'categories.subtitle': 'Choisissez l\'aventure qui vous convient',
    'cat.nature': 'Tourisme Naturel',
    'cat.nature.count': '12 destinations',
    'cat.adventure': 'Aventures',
    'cat.adventure.count': '8 activités',
    'cat.culture': 'Tourisme Culturel',
    'cat.culture.count': '6 sites',
    'cat.sports': 'Sports de Montagne',
    'cat.sports.count': '5 activités',
    'map.title': 'Localisation d\'Azilal',
    'map.desc': 'Située au cœur du Haut Atlas, à 220 km au sud-est de Casablanca, Azilal offre une diversité naturelle et culturelle unique',
    'map.f1.title': 'Nature Spectaculaire',
    'map.f1.desc': 'Montagnes, vallées et forêts diverses',
    'map.f2.title': 'Patrimoine Amazigh',
    'map.f2.desc': 'Villages traditionnels et culture riche',
    'map.f3.title': 'Climat Doux',
    'map.f3.desc': 'Idéal pour visiter toute l\'année',
    'footer.about': 'Tourisme Azilal est votre passerelle pour découvrir les plus beaux paysages naturels et la culture amazighe authentique de la région d\'Azilal',
    'footer.links': 'Liens Rapides',
    'footer.contact': 'Informations de Contact',
    'footer.follow': 'Suivez-nous',
    'footer.copyright': 'Tous droits réservés',
    'chat.title': 'Contactez-nous',
    'chat.subtitle': 'Nous sommes là pour vous aider à planifier votre voyage',
    'chat.placeholder': 'Tapez votre message ici...',
    'chat.send': 'Envoyer',
    'chat.welcome': 'Bonjour! Comment puis-je vous aider à planifier votre voyage à Azilal?',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Abonnez-vous pour recevoir les dernières offres et nouvelles',
    'footer.email': 'Votre email',
    'footer.subscribe': 'S\'abonner',
  },
  ber: {
    'nav.home': 'ⴰⵎⵣⵡⴰⵔⵓ',
    'nav.destinations': 'ⵉⵎⴷⴰⵏⵏ',
    'nav.activities': 'ⵜⵉⵔⴰⵔⵉⵏ',
    'nav.about': 'ⴼ ⴰⵣⵉⵍⴰⵍ',
    'nav.contact': 'ⵏⵎⵥⴰ',
    'hero.badge': 'ⴰⵎⴷⴰⵏ ⵏⵏⴽ ⵉⵙⵙⵏ ⵎⵓⵔⴰⴽⵓⵛ',
    'hero.title': 'ⵙⵏⵓⴱⵔⵛ ⴰⵙⵔⴽⵉⵙ ⵏ ⴰⵣⵉⵍⴰⵍ',
    'hero.subtitle': 'ⴷⴰⵔ ⵉⵡⴷⵉⵡⵏ ⵏ ⴰⵟⵍⴰⵙ ⴷ ⵉⵡⴰⵍⵉⵢⵏ ⵉⵣⵓⵣⵣⴰⵏⵏ, ⵙⵏⵓⴱⵔⵛ ⵜⵉⵍⴰⵍ ⵏ ⵜⴰⴷⴰⵍⵉⵜ ⴷ ⵜⴰⵖⵍⵉⵜ ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵎⵓⵍⵏⵜ',
    'hero.cta': 'ⴱⴷⵓ ⴰⵏⴰⵡⵏ ⵏⵏⴽ',
    'featured.title': 'ⵉⵎⴷⴰⵏⵏ ⵉⵎⵇⵓⵔⵏ',
    'featured.subtitle': 'ⵙⵏⵓⴱⵔⵛ ⵜⵉⵍⴰⵍ ⵏⵏⵉⵢⵏⵉⵏ ⴷⴰⵔ ⵜⵎⵏⴰⴹⵜ ⵏ ⴰⵣⵉⵍⴰⵍ',
    'featured.1.title': 'ⴰⵖⵏⵛⴰⵡ ⵏ ⴱⵉⵏ ⵍⵡⵉⴷⴰⵏ',
    'featured.1.desc': 'ⴰⵖⵏⵛⴰⵡ ⵉⵛⵏⵏⵓⵏ ⵉⵜⵜⴰⵡⵢⵏ ⵙ ⵉⵡⴷⵉⵡⵏ ⵏ ⴰⵟⵍⴰⵙ, ⵉⵜⵜⵓⵙⵏ ⵉ ⵜⵉⵔⴰⵔⵉⵏ ⵏ ⵡⴰⵎⴰⵏ ⴷ ⵜⵉⵎⵣⵓⵔⵉ',
    'featured.1.badge': 'ⵉⵎⵇⵓⵔ',
    'featured.2.title': 'ⵉⵔⵣⵣⵉⵜⵏ ⵏ ⵜⵉⵙⵏⵉⵔⵜ',
    'featured.2.desc': 'ⵉⵔⵣⵣⵉⵜⵏ ⵉⵜⵜⵔⵣⵢⵏ ⵙⴳ ⵉⵣⴳⴰⵏ ⵉⵖⴱⵉⴱⵏ ⴷⴰⵔ ⵜⴰⵖⵍⴰⵎⵜ ⵏ ⵉⵖⵏⵛⴰⵡⵏ',
    'featured.2.badge': 'ⵜⴰⴷⴰⵍⵉⵜ',
    'featured.3.title': 'ⵉⵖⵔⵎⴰⵏ ⵏ ⴰⵢⵜ ⴱⵓⵀⴷⴷⵓ',
    'featured.3.desc': 'ⵉⵖⵔⵎⴰⵏ ⵉⵎⴰⵣⵉⵖⵏ ⵉⵎⵓⵍⵏ ⵉⴳⵎⴰⵢⵏ ⵜⵉⵖⵍⵉⵜ ⴷ ⵉⴳⵏⵉⵜⵏ ⵉⵣⴷⴰⵢⵏ',
    'featured.3.badge': 'ⵜⵉⵖⵍⵉⵜ',
    'stats.visitors': 'ⵉⵏⴱⵖⵉⵡⵏ ⵙ ⵓⵙⴳⴳⵯⴰⵙ',
    'stats.trails': 'ⵉⴱⵔⴷⴰⵏ ⵏ ⵜⴰⴷⴰⵍⵉⵜ',
    'stats.heritage': 'ⵉⵎⴷⴰⵏ ⵏ ⵓⴳⵎⴰⵢ',
    'stats.hospitality': 'ⵉⵎⴰⵍⴰⵢⵏ',
    'destinations.title': 'ⵉⵎⴷⴰⵏⵏ ⵏ ⵜⵎⵙⵉⴷⴰⵜ',
    'destinations.subtitle': 'ⵙⵏⵓⴱⵔⵛ ⵜⵉⵍⴰⵍ ⵏ ⴰⵣⵉⵍⴰⵍ',
    'destinations.view': 'ⵣⵔⵉ ⵉⵜⵜⴼⴰⵍⵙⵏ',
    'categories.title': 'ⵉⵏⴰⵡⵏ ⵏ ⵜⵎⵙⵉⴷⴰⵜ',
    'categories.subtitle': 'ⵙⵜⵉ ⴰⵏⴰⵡ ⵏ ⵜⵓⵔⴰⵔⵜ ⵉ ⵏⵏⴽ',
    'cat.nature': 'ⵜⴰⵎⵙⵉⴷⴰⵜ ⵏ ⵜⴰⴷⴰⵍⵉⵜ',
    'cat.nature.count': '12 ⵉⵎⴷⴰⵏⵏ',
    'cat.adventure': 'ⵜⵉⵔⴰⵔⵉⵏ',
    'cat.adventure.count': '8 ⵜⵉⵔⴰⵔⵉⵏ',
    'cat.culture': 'ⵜⴰⵎⵙⵉⴷⴰⵜ ⵜⴰⴷⵍⵙⴰⵏⵜ',
    'cat.culture.count': '6 ⵉⵎⴷⴰⵏⵏ',
    'cat.sports': 'ⵜⵉⵔⴰⵔⵉⵏ ⵏ ⵓⵡⴷⵉⵡ',
    'cat.sports.count': '5 ⵜⵉⵔⴰⵔⵉⵏ',
    'map.title': 'ⴰⵙⴷⵡⵓⵙ ⵏ ⴰⵣⵉⵍⴰⵍ',
    'map.desc': 'ⵜⵍⵍⴰ ⴰⵣⵉⵍⴰⵍ ⴷⴰⵔ ⵓⵡⵜⵜⵓⵏ ⵏ ⵉⵡⴷⵉⵡⵏ ⵏ ⴰⵟⵍⴰⵙ ⴰⵎⵇⵇⵔⴰⵏ, 220 ⴽⵎ ⵙ ⵓⵏⵣⵓⵍ ⴰⵙⵎⴷⴰⵢ ⵏ ⴽⴰⵢⵢⴰⴱⵍⴰⵏⴽⴰ',
    'map.f1.title': 'ⵜⴰⴷⴰⵍⵉⵜ ⵉⵜⵜⵔⵣⵢⵏ',
    'map.f1.desc': 'ⵉⵡⴷⵉⵡⵏ ⴷ ⵉⵡⴰⵍⵉⵢⵏ ⴷ ⵜⴰⵖⵍⴰⵎⵜ',
    'map.f2.title': 'ⴰⵖⵎⴰⵢ ⴰⵎⴰⵣⵉⵖ',
    'map.f2.desc': 'ⵉⵖⵔⵎⴰⵏ ⵉⵎⵓⵍⵏ ⴷ ⵜⴰⴷⵍⵙⴰ',
    'map.f3.title': 'ⴰⵏⴰⵡ ⵉⵜⵜⵓⴷⵏ',
    'map.f3.desc': 'ⵉⵜⵜⵓⵙⵏ ⵉ ⵜⵎⵙⵉⴷⴰⵜ',
    'footer.about': 'ⵜⴰⵎⵙⵉⴷⴰⵜ ⵏ ⴰⵣⵉⵍⴰⵍ ⵜⴳⴰ ⵜⴰⵡⵡⵓⵔⵜ ⵏⵏⴽ ⵉⴳ ⵜⵙⵏⵓⴱⵔⵛⵉⴷ ⵜⵉⵍⴰⵍ ⵏ ⵜⴰⴷⴰⵍⵉⵜ ⴷ ⵜⴰⵖⵍⵉⵜ ⵜⴰⵎⴰⵣⵉⵖⵜ',
    'footer.links': 'ⵜⵉⵖⵍⴰⴼⵉⵏ',
    'footer.contact': 'ⵉⵏⵏⴰⵡⵏ ⵏ ⵜⵏⵣⵓⵜ',
    'footer.follow': 'ⵔⵥⵎⵏⴷ',
    'footer.copyright': 'ⵉⵖⵓⵔⵉⵡⵏ ⴷⵓⵔⵏ ⵉⵙⵙⴼⴽⵏ',
    'chat.title': 'ⵏⵎⵥⴰ',
    'chat.subtitle': 'ⵏⴽⵏⵉ ⵏⵏⵖ ⵏⴰⵢ ⵏⵎⵓⵏ ⴰⵏⴰⵡⵏ ⵏⵏⴽ',
    'chat.placeholder': 'ⴰⵔⴰ ⵜⴰⵏⴰⵡⵜ ⵏⵏⴽ ⴷⴰ...',
    'chat.send': 'ⴰⵣⵏ',
    'chat.welcome': 'ⴰⵣⵓⵍ! ⵎⴰⵎⴽ ⴰⵔ ⵜⵓⵙⵉⴷⵉⴷ ⴰⵏⴰⵡⵏ ⵏⵏⴽ ⵙ ⴰⵣⵉⵍⴰⵍ?',
    'footer.newsletter': 'ⴰⵢⵙⵙⴰⵢⵢⵏ',
    'footer.newsletter.desc': 'ⵔⵥⵎ ⵉⴳ ⵜⵔⵉⴷ ⵉⵙⵙⵏⵏ ⵉⵏⵏⴰⵢⵏ',
    'footer.email': 'ⵉⵎⴰⵢⵍ ⵏⵏⴽ',
    'footer.subscribe': 'ⵔⵥⵎ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('ar');

  const setLang = useCallback((newLang: Lang) => {
    setLangState(newLang);
    document.documentElement.lang = newLang;
    document.documentElement.dir = newLang === 'ar' || newLang === 'ber' ? 'rtl' : 'ltr';
  }, []);

  const t = useCallback(
    (key: string) => translations[lang][key] || key,
    [lang]
  );

  const isRTL = lang === 'ar' || lang === 'ber';

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
  }, [lang, isRTL]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
