import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from 'react';

export type Lang = 'ar' | 'en' | 'fr' | 'ber';

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Lang, Record<string, string>> = {
  ar: {
    'nav.home': 'الرئيسية',
    'nav.destinations': 'الوجهات',
    'nav.hotels': 'الفنادق',
    'nav.restaurants': 'المطاعم',
    'nav.cafes': 'المقاهي',
    'nav.cars': 'السيارات',
    'nav.activities': 'الأنشطة',
    'nav.planning': 'خطّط لزيارتك',
    'nav.localProducts': 'المنتجات والجمعيات',
    'nav.about': 'عن أزيلال',
    'nav.contact': 'تواصل معنا',
    'hero.badge': 'وجهتك التالية: مدينة أزيلال - المغرب',
    'hero.title': 'اكتشف سحر أزيلال',
    'hero.subtitle': 'بين جبال الأطلس الشاهقة والوديان الخضراء، اكتشف جمال الطبيعة وثقافة الأمازيغ الأصيلة',
    'hero.cta': 'ابدأ رحلتك',
    'featured.title': 'أبرز الوجهات',
    'featured.subtitle': 'استكشف أجمل الأماكن في إقليم أزيلال',
    'featured.localLabel': 'اختيار للاستكشاف',
    'featured.1.title': 'بحيرة بين الويدان',
    'featured.1.desc': 'بحيرة ساحرة محاطة بجبال الأطلس الشاهقة، مثالية للرياضات المائية والتخييم',
    'featured.1.badge': 'مميز',
    'featured.2.title': 'شلالات تيسنيرت',
    'featured.2.desc': 'شلالات خلابة تنحدر من صخور الحمرة وسط غابات الأرز',
    'featured.2.badge': 'طبيعة',
    'featured.3.title': 'قرى أيت بومهدى',
    'featured.3.desc': 'قرى أمازيغية تقليدية تحافظ على التراث الثقافي والتقاليد العريقة',
    'featured.3.badge': 'ثقافة',
    'stats.visitors': 'زائر سنوياً',
    'stats.trails': 'مسار طبيعي',
    'stats.heritage': 'موقع تراثي',
    'stats.hospitality': 'مكان إقامة',
    'destinations.title': 'وجهات سياحية',
    'destinations.subtitle': 'اكتشف جمال أزيلال المتنوع',
    'destinations.view': 'عرض التفاصيل',
    'categories.title': 'أنواع السياحة',
    'categories.subtitle': 'اختر نوع المغامرة المناسبة لك',
    'categories.localProductsCta': 'اكتشف المنتجات الطبيعية والجمعيات المحلية',
    'cat.nature': 'السياحة الطبيعية',
    'cat.nature.count': '12 وجهة',
    'cat.adventure': 'المغامرات',
    'cat.adventure.count': '8 نشاطات',
    'cat.culture': 'السياحة الثقافية',
    'cat.culture.count': '6 مواقع',
    'cat.sports': 'الرياضات الجبلية',
    'cat.sports.count': '5 أنشطة',
    'cat.localProducts': 'المنتجات الطبيعية',
    'cat.localProducts.count': 'منتجات محلية',
    'map.title': 'موقع أزيلال',
    'map.desc': 'تقع أزيلال في قلب جبال الأطلس الكبير، على بعد 220 كم جنوب شرق الدار البيضاء، وتتميز بتنوع طبيعي وثقافي فريد',
    'map.f1.title': 'طبيعة خلابة',
    'map.f1.desc': 'جبال ووديان وغابات متنوعة',
    'map.f2.title': 'تراث أمازيغي',
    'map.f2.desc': 'قرى تقليدية وثقافة عريقة',
    'map.f3.title': 'مناخ معتدل',
    'map.f3.desc': 'مثالية للزيارة طوال السنة',
    'footer.about': 'ADRAR هي بوابتك لاكتشاف أجمل ما تقدمه مدينة أزيلال من طبيعة خلابة وثقافة أمازيغية أصيلة',
    'footer.links': 'روابط سريعة',
    'footer.contact': 'معلومات التواصل',
    'footer.follow': 'تابعنا',
    'footer.copyright': 'جميع الحقوق محفوظة',
    'chat.title': 'تواصل معنا',
    'chat.subtitle': 'نحن هنا لمساعدتك في التخطيط لرحلتك',
    'chat.placeholder': 'اكتب رسالتك هنا...',
    'chat.name': 'الاسم',
    'chat.email': 'البريد الإلكتروني للرد',
    'chat.emailRequired': 'أدخل بريدك الإلكتروني حتى نتمكن من الرد عليك.',
    'chat.send': 'إرسال',
    'chat.welcome': 'مرحباً! كيف يمكنني مساعدتك في التخطيط لرحلتك إلى أزيلال؟',
    'chat.received': 'تم استلام رسالتك. سنجيبك عبر البريد الإلكتروني أو واتساب عند توفر الرقم الرسمي.',
    'chat.sending': 'جارٍ إرسال رسالتك...',
    'chat.error': 'تعذر إرسال الرسالة حالياً. حاول مرة أخرى لاحقاً.',
    'chat.whatsappUnavailable': 'التواصل عبر واتساب غير متاح مؤقتاً.',
    'footer.newsletter': 'النشرة البريدية',
    'footer.newsletter.desc': 'اشترك لتصلك أحدث العروض والأخبار',
    'footer.email': 'بريدك الإلكتروني',
    'footer.subscribe': 'اشترك',
    'nav.login': 'تسجيل الدخول',
    'nav.myBookings': 'حجوزاتي',
    'nav.loginOnMainSite': 'تسجيل الدخول على الموقع الرئيسي — انقر هنا',
    'pwa.install': 'تنصيب التطبيق',
    'choice.title': 'مرحباً بك في أدرار! شنو بغيتي تدير؟',
    'choice.guestTitle': 'بغيت نحجز',
    'choice.guestDesc': 'شوف الفنادق والمطاعم والمقاهي والسيارات وحجز اللي عجبك',
    'choice.ownerTitle': 'عندي فندق / مقهى / سيارة',
    'choice.ownerDesc': 'دخل للوحة التحكم باش تدير الحوايج ديالك',
    'choice.skip': 'تخطى',
    'guest.title': 'حجوزاتي',
    'guest.subtitle': 'تابع حالة حجوزاتك وأدرها من هنا',
    'guest.empty.title': 'ما عندك حتى حجز',
    'guest.empty.desc': 'باش تبدا، حجز فندق ولا كراية سيارة من الموقع وغادي تلقى حجزاتك هنا',
    'guest.empty.cta': 'شوف الفنادق',
    'guest.status.pending': 'قيد الانتظار',
    'guest.status.confirmed': 'مؤكدة',
    'guest.status.cancelled': 'ملغية',
    'guest.status.completed': 'مكتملة',
    'guest.pay_pending': 'غير مدفوعة',
    'guest.pay_paid': 'مدفوعة',
    'guest.pay_arrival': 'الدفع عند الوصول',
    'guest.pay_card': 'بطاقة بنكية',
    'guest.cancel': 'إلغاء الحجز',
    'guest.cancelConfirm': 'واش متأكد بغيتي تلغي هذا الحجز؟ هادشي مايمكنش يرجع.',
    'guest.cancelYes': 'إييه، لغاي',
    'guest.cancelNo': 'لا، خليني',
    'guest.cancelled_msg': 'تلغاء الحجز بنجاح',
    'guest.error_cancel': 'ممكنش نتلغاو الحجز، حاول مرة خرا',
    'guest.type_hotel': 'فندق',
    'guest.type_car': 'كراية سيارة',
    'guest.dates': 'التواريخ',
    'guest.price': 'الثمن الكلي',
    'guest.guest_info': 'معلوماتك',
    'guest.notes': 'ملاحظات',
    'guest.pay_status': 'حالة الأداء',
    'guest.booking_date': 'تاريخ الحجز',
  },
  en: {
    'nav.home': 'Home',
    'nav.destinations': 'Destinations',
    'nav.hotels': 'Hotels',
    'nav.restaurants': 'Restaurants',
    'nav.cafes': 'Cafés',
    'nav.cars': 'Car Rental',
    'nav.activities': 'Activities',
    'nav.planning': 'Plan your visit',
    'nav.localProducts': 'Products & Associations',
    'nav.about': 'About ADRAR',
    'nav.contact': 'Contact Us',
    'hero.badge': 'Your next destination: Azilal City, Morocco',
    'hero.title': 'Discover the Magic of ADRAR',
    'hero.subtitle': 'Between towering Atlas Mountains and lush green valleys, discover the beauty of nature and authentic Amazigh culture',
    'hero.cta': 'Start Your Journey',
    'featured.title': 'Top Destinations',
    'featured.subtitle': 'Explore the most beautiful places in the Azilal region',
    'featured.localLabel': 'Worth exploring',
    'featured.1.title': 'Bin el Ouidane Lake',
    'featured.1.desc': 'A magical lake surrounded by towering Atlas Mountains, perfect for water sports and camping',
    'featured.1.badge': 'Featured',
    'featured.2.title': 'Tisnirt Waterfalls',
    'featured.2.desc': 'Stunning waterfalls cascading from red sandstone cliffs amid cedar forests',
    'featured.2.badge': 'Nature',
    'featured.3.title': 'Ait Bouhaddou Villages',
    'featured.3.desc': 'Traditional Amazigh villages preserving rich cultural heritage and ancient traditions',
    'featured.3.badge': 'Culture',
    'stats.visitors': 'Visitors Annually',
    'stats.trails': 'Nature Trails',
    'stats.heritage': 'Heritage Sites',
    'stats.hospitality': 'Accommodations',
    'destinations.title': 'Tourist Destinations',
    'destinations.subtitle': 'Discover the diverse beauty of Azilal',
    'destinations.view': 'View Details',
    'categories.title': 'Types of Tourism',
    'categories.subtitle': 'Choose the adventure that suits you',
    'categories.localProductsCta': 'Discover natural products and local associations',
    'cat.nature': 'Nature Tourism',
    'cat.nature.count': '12 destinations',
    'cat.adventure': 'Adventures',
    'cat.adventure.count': '8 activities',
    'cat.culture': 'Cultural Tourism',
    'cat.culture.count': '6 sites',
    'cat.sports': 'Mountain Sports',
    'cat.sports.count': '5 activities',
    'cat.localProducts': 'Natural Products',
    'cat.localProducts.count': 'Local products',
    'map.title': 'Location of Azilal',
    'map.desc': 'Azilal is located in the heart of the High Atlas Mountains, 220 km southeast of Casablanca, featuring unique natural and cultural diversity',
    'map.f1.title': 'Stunning Nature',
    'map.f1.desc': 'Mountains, valleys, and diverse forests',
    'map.f2.title': 'Amazigh Heritage',
    'map.f2.desc': 'Traditional villages and rich culture',
    'map.f3.title': 'Mild Climate',
    'map.f3.desc': 'Perfect for visiting year-round',
    'footer.about': 'ADRAR is your gateway to discovering the most beautiful natural landscapes and authentic Amazigh culture of Azilal city, Morocco',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact Information',
    'footer.follow': 'Follow Us',
    'footer.copyright': 'All rights reserved',
    'chat.title': 'Contact Us',
    'chat.subtitle': 'We are here to help you plan your trip',
    'chat.placeholder': 'Type your message here...',
    'chat.name': 'Name',
    'chat.email': 'Email for a reply',
    'chat.emailRequired': 'Enter your email so we can reply to you.',
    'chat.send': 'Send',
    'chat.welcome': 'Hello! How can I help you plan your trip to Azilal?',
    'chat.received': 'Your message was received. We will reply by email or WhatsApp when the official number is available.',
    'chat.sending': 'Sending your message...',
    'chat.error': 'The message could not be sent right now. Please try again later.',
    'chat.whatsappUnavailable': 'WhatsApp contact is temporarily unavailable.',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Subscribe to get the latest offers and news',
    'footer.email': 'Your email',
    'footer.subscribe': 'Subscribe',
    'nav.login': 'Login',
    'nav.myBookings': 'My Bookings',
    'nav.loginOnMainSite': 'Login on the main site — click here',
    'pwa.install': 'Install App',
    'choice.title': 'Welcome to ADRAR! What would you like to do?',
    'choice.guestTitle': 'I want to book',
    'choice.guestDesc': 'Browse hotels, restaurants, cafés and cars, and book what you like',
    'choice.ownerTitle': 'I own a property / a car',
    'choice.ownerDesc': 'Open the dashboard to manage your listings',
    'choice.skip': 'Skip',
    'guest.title': 'My Bookings',
    'guest.subtitle': 'Track and manage your reservations from here',
    'guest.empty.title': 'You have no bookings yet',
    'guest.empty.desc': 'To get started, book a hotel or rent a car from the site and you will find your bookings here',
    'guest.empty.cta': 'Browse hotels',
    'guest.status.pending': 'Pending',
    'guest.status.confirmed': 'Confirmed',
    'guest.status.cancelled': 'Cancelled',
    'guest.status.completed': 'Completed',
    'guest.pay_pending': 'Unpaid',
    'guest.pay_paid': 'Paid',
    'guest.pay_arrival': 'Pay on Arrival',
    'guest.pay_card': 'Credit Card',
    'guest.cancel': 'Cancel Booking',
    'guest.cancelConfirm': 'Are you sure you want to cancel this booking? This cannot be undone.',
    'guest.cancelYes': 'Yes, cancel it',
    'guest.cancelNo': 'No, keep it',
    'guest.cancelled_msg': 'Booking cancelled successfully',
    'guest.error_cancel': 'Could not cancel the booking, please try again',
    'guest.type_hotel': 'Hotel',
    'guest.type_car': 'Car Rental',
    'guest.dates': 'Dates',
    'guest.price': 'Total Price',
    'guest.guest_info': 'Your Information',
    'guest.notes': 'Notes',
    'guest.pay_status': 'Payment Status',
    'guest.booking_date': 'Booking Date',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.destinations': 'Destinations',
    'nav.hotels': 'Hôtels',
    'nav.restaurants': 'Restaurants',
    'nav.cafes': 'Cafés',
    'nav.cars': 'Location',
    'nav.activities': 'Activités',
    'nav.planning': 'Planifier la visite',
    'nav.localProducts': 'Produits et associations',
    'nav.about': 'À propos',
    'nav.contact': 'Contactez-nous',
    'hero.badge': "Votre prochaine destination : Ville d'Azilal, Maroc",
    'hero.title': 'Découvrez la Magie d\'ADRAR',
    'hero.subtitle': 'Entre les montagnes majestueuses de l\'Atlas et les vallées verdoyantes, découvrez la beauté de la nature et la culture amazighe authentique',
    'hero.cta': 'Commencez votre voyage',
    'featured.title': 'Destinations Phares',
    'featured.subtitle': 'Explorez les plus beaux endroits de la région d\'Azilal',
    'featured.localLabel': 'À découvrir',
    'featured.1.title': 'Lac de Bin el Ouidane',
    'featured.1.desc': 'Un lac magique entouré par les montagnes de l\'Atlas, idéal pour les sports nautiques et le camping',
    'featured.1.badge': 'Vedette',
    'featured.2.title': 'Cascades de Tisnirt',
    'featured.2.desc': 'Des cascades spectaculaires tombant des falaises de grès rouge parmi les forêts de cèdres',
    'featured.2.badge': 'Nature',
    'featured.3.title': 'Villages d\'Ait Bouhaddou',
    'featured.3.desc': 'Des villages amazighs traditionnels préservant un riche patrimoine culturel et des traditions anciennes',
    'featured.3.badge': 'Culture',
    'stats.visitors': 'Visiteurs par an',
    'stats.trails': 'Sentiers naturels',
    'stats.heritage': 'Sites patrimoniaux',
    'stats.hospitality': 'Hébergements',
    'destinations.title': 'Destinations Touristiques',
    'destinations.subtitle': 'Découvrez la beauté diversifiée d\'Azilal',
    'destinations.view': 'Voir les détails',
    'categories.title': 'Types de Tourisme',
    'categories.subtitle': 'Choisissez l\'aventure qui vous convient',
    'categories.localProductsCta': 'Découvrez les produits naturels et les associations locales',
    'cat.nature': 'Tourisme Naturel',
    'cat.nature.count': '12 destinations',
    'cat.adventure': 'Aventures',
    'cat.adventure.count': '8 activités',
    'cat.culture': 'Tourisme Culturel',
    'cat.culture.count': '6 sites',
    'cat.sports': 'Sports de Montagne',
    'cat.sports.count': '5 activités',
    'cat.localProducts': 'Produits naturels',
    'cat.localProducts.count': 'Produits locaux',
    'map.title': 'Localisation d\'Azilal',
    'map.desc': 'Située au cœur du Haut Atlas, à 220 km au sud-est de Casablanca, Azilal offre une diversité naturelle et culturelle unique',
    'map.f1.title': 'Nature Spectaculaire',
    'map.f1.desc': 'Montagnes, vallées et forêts diverses',
    'map.f2.title': 'Patrimoine Amazigh',
    'map.f2.desc': 'Villages traditionnels et culture riche',
    'map.f3.title': 'Climat Doux',
    'map.f3.desc': 'Idéal pour visiter toute l\'année',
    'footer.about': 'ADRAR est votre passerelle pour découvrir les plus beaux paysages naturels et la culture amazighe authentique de la ville d\'Azilal, Maroc',
    'footer.links': 'Liens Rapides',
    'footer.contact': 'Informations de Contact',
    'footer.follow': 'Suivez-nous',
    'footer.copyright': 'Tous droits réservés',
    'chat.title': 'Contactez-nous',
    'chat.subtitle': 'Nous sommes là pour vous aider à planifier votre voyage',
    'chat.placeholder': 'Tapez votre message ici...',
    'chat.name': 'Nom',
    'chat.email': 'E-mail pour recevoir une réponse',
    'chat.emailRequired': 'Saisissez votre e-mail afin que nous puissions vous répondre.',
    'chat.send': 'Envoyer',
    'chat.welcome': 'Bonjour! Comment puis-je vous aider à planifier votre voyage à Azilal?',
    'chat.received': 'Votre message a été reçu. Nous vous répondrons par e-mail ou WhatsApp lorsque le numéro officiel sera disponible.',
    'chat.sending': 'Envoi de votre message...',
    'chat.error': 'Le message ne peut pas être envoyé pour le moment. Réessayez plus tard.',
    'chat.whatsappUnavailable': 'Le contact WhatsApp est temporairement indisponible.',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Abonnez-vous pour recevoir les dernières offres et nouvelles',
    'footer.email': 'Votre email',
    'footer.subscribe': 'S\'abonner',
    'nav.login': 'Connexion',
    'nav.myBookings': 'Mes Réservations',
    'nav.loginOnMainSite': 'Se connecter sur le site principal — cliquez ici',
    'pwa.install': "Installer l'app",
    'choice.title': 'Bienvenue chez ADRAR ! Que souhaitez-vous faire ?',
    'choice.guestTitle': 'Je veux réserver',
    'choice.guestDesc': 'Parcourez hôtels, restaurants, cafés et voitures et réservez ce qui vous plaît',
    'choice.ownerTitle': 'J’ai un établissement / une voiture',
    'choice.ownerDesc': 'Ouvrez le tableau de bord pour gérer vos annonces',
    'choice.skip': 'Passer',
    'guest.title': 'Mes Réservations',
    'guest.subtitle': 'Suivez et gérez vos réservations depuis ici',
    'guest.empty.title': 'Vous n\'avez aucune réservation',
    'guest.empty.desc': 'Pour commencer, réservez un hôtel ou louez une voiture et vous trouverez vos réservations ici',
    'guest.empty.cta': 'Voir les hôtels',
    'guest.status.pending': 'En attente',
    'guest.status.confirmed': 'Confirmée',
    'guest.status.cancelled': 'Annulée',
    'guest.status.completed': 'Terminée',
    'guest.pay_pending': 'Non payée',
    'guest.pay_paid': 'Payée',
    'guest.pay_arrival': 'Paiement à l\'arrivée',
    'guest.pay_card': 'Carte bancaire',
    'guest.cancel': 'Annuler la réservation',
    'guest.cancelConfirm': 'Êtes-vous sûr de vouloir annuler cette réservation ? Cette action est irréversible.',
    'guest.cancelYes': 'Oui, annuler',
    'guest.cancelNo': 'Non, garder',
    'guest.cancelled_msg': 'Réservation annulée avec succès',
    'guest.error_cancel': 'Impossible d\'annuler la réservation, réessayez',
    'guest.type_hotel': 'Hôtel',
    'guest.type_car': 'Location de voiture',
    'guest.dates': 'Dates',
    'guest.price': 'Prix total',
    'guest.guest_info': 'Vos informations',
    'guest.notes': 'Notes',
    'guest.pay_status': 'Statut du paiement',
    'guest.booking_date': 'Date de réservation',
  },
  ber: {
    'nav.home': 'ⴰⵎⵣⵡⴰⵔⵓ',
    'nav.destinations': 'ⵉⵎⴷⴰⵏⵏ',
    'nav.hotels': 'ⵉⵙⵏⴷⵇⵏ',
    'nav.restaurants': 'ⵉⵎⵙⵙⴽⵏ',
    'nav.cafes': 'ⵉⵇⵀⵡⴰⵢⵏ',
    'nav.cars': 'ⵜⴰⵙⵍⵍⴰⵙⵜ',
    'nav.activities': 'ⵜⵉⵔⴰⵔⵉⵏ',
    'nav.planning': 'ⵙⵎⵓⵜⵜⵉ ⵉ ⵓⵔⴰⵔ',
    'nav.localProducts': 'ⵉⵎⵥⵍⴰⵢ ⴷ ⵜⵎⵙⵙⵉⵔⵉⵏ',
    'nav.about': 'ⴼ ⴰⴷⵔⴰⵔ',
    'nav.contact': 'ⵏⵎⵥⴰ',
    'hero.badge': 'ⴰⵎⴷⴰⵏ ⵏⵏⴽ: ⵜⵖⵔⵎⵜ ⵏ ⴰⵣⵉⵍⴰⵍ - ⵎⵓⵕⵕⴽⵓⵛ',
    'hero.title': 'ⵙⵏⵓⴱⵔⵛ ⴰⵙⵔⴽⵉⵙ ⵏ ⴰⴷⵔⴰⵔ',
    'hero.subtitle': 'ⴷⴰⵔ ⵉⵡⴷⵉⵡⵏ ⵏ ⴰⵟⵍⴰⵙ ⴷ ⵉⵡⴰⵍⵉⵢⵏ ⵉⵣⵓⵣⵣⴰⵏⵏ, ⵙⵏⵓⴱⵔⵛ ⵜⵉⵍⴰⵍ ⵏ ⵜⴰⴷⴰⵍⵉⵜ ⴷ ⵜⴰⵖⵍⵉⵜ ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵎⵓⵍⵏⵜ',
    'hero.cta': 'ⴱⴷⵓ ⴰⵏⴰⵡⵏ ⵏⵏⴽ',
    'featured.title': 'ⵉⵎⴷⴰⵏⵏ ⵉⵎⵇⵓⵔⵏ',
    'featured.subtitle': 'ⵙⵏⵓⴱⵔⵛ ⵜⵉⵍⴰⵍ ⵏⵏⵉⵢⵏⵉⵏ ⴷⴰⵔ ⵜⵎⵏⴰⴹⵜ ⵏ ⴰⵣⵉⵍⴰⵍ',
    'featured.localLabel': 'ⴰⵙⵙⵏⵓⴱⵔⵛ',
    'featured.1.title': 'ⴰⵖⵏⵛⴰⵡ ⵏ ⴱⵉⵏ ⵍⵡⵉⴷⴰⵏ',
    'featured.1.desc': 'ⴰⵖⵏⵛⴰⵡ ⵉⵛⵏⵏⵓⵏ ⵉⵜⵜⴰⵡⵢⵏ ⵙ ⵉⵡⴷⵉⵡⵏ ⵏ ⴰⵟⵍⴰⵙ, ⵉⵜⵜⵓⵙⵏ ⵉ ⵜⵉⵔⴰⵔⵉⵏ ⵏ ⵡⴰⵎⴰⵏ ⴷ ⵜⵉⵎⵣⵓⵔⵉ',
    'featured.1.badge': 'ⵉⵎⵇⵓⵔ',
    'featured.2.title': 'ⵉⵔⵣⵣⵉⵜⵏ ⵏ ⵜⵉⵙⵏⵉⵔⵜ',
    'featured.2.desc': 'ⵉⵔⵣⵣⵉⵜⵏ ⵉⵜⵜⵔⵣⵢⵏ ⵙⴳ ⵉⵣⴳⴰⵏ ⵉⵖⴱⵉⴱⵏ ⴷⴰⵔ ⵜⴰⵖⵍⴰⵎⵜ ⵏ ⵉⵖⵏⵛⴰⵡⵏ',
    'featured.2.badge': 'ⵜⴰⴷⴰⵍⵉⵜ',
    'featured.3.title': 'ⵉⵖⵔⵎⴰⵏ ⵏ ⴰⵢⵜ ⴱⵓⵀⴷⴷⵓ',
    'featured.3.desc': 'ⵉⵖⵔⵎⴰⵏ ⵉⵎⴰⵣⵉⵖⵏ ⵉⵎⵓⵍⵏ ⵉⴳⵎⴰⵢⵏ ⵜⵉⵖⵍⵉⵜ ⴷ ⵉⴳⵏⵉⵜⵏ ⵉⵣⴷⴰⵢⵏ',
    'featured.3.badge': 'ⵜⵉⵖⵍⵉⵜ',
    'stats.visitors': 'ⵉⵏⴱⵖⵉⵡⵏ ⵙ ⵓⵙⴳⴳⵯⴰⵙ',
    'stats.trails': 'ⵉⴱⵔⴷⴰⵏ ⵏ ⵜⴰⴷⴰⵍⵉⵜ',
    'stats.heritage': 'ⵉⵎⴷⴰⵏ ⵏ ⵓⴳⵎⴰⵢ',
    'stats.hospitality': 'ⵉⵎⴰⵍⴰⵢⵏ',
    'destinations.title': 'ⵉⵎⴷⴰⵏⵏ ⵏ ⵜⵎⵙⵉⴷⴰⵜ',
    'destinations.subtitle': 'ⵙⵏⵓⴱⵔⵛ ⵜⵉⵍⴰⵍ ⵏ ⴰⵣⵉⵍⴰⵍ',
    'destinations.view': 'ⵣⵔⵉ ⵉⵜⵜⴼⴰⵍⵙⵏ',
    'categories.title': 'ⵉⵏⴰⵡⵏ ⵏ ⵜⵎⵙⵉⴷⴰⵜ',
    'categories.subtitle': 'ⵙⵜⵉ ⴰⵏⴰⵡ ⵏ ⵜⵓⵔⴰⵔⵜ ⵉ ⵏⵏⴽ',
    'categories.localProductsCta': 'ⵙⵏⵓⴱⵔⵛ ⵉⵎⵥⵍⴰⵢ ⵏ ⵓⵎⵣⵔⵓⵢ ⴷ ⵜⵎⵙⵙⵉⵔⵉⵏ',
    'cat.nature': 'ⵜⴰⵎⵙⵉⴷⴰⵜ ⵏ ⵜⴰⴷⴰⵍⵉⵜ',
    'cat.nature.count': '12 ⵉⵎⴷⴰⵏⵏ',
    'cat.adventure': 'ⵜⵉⵔⴰⵔⵉⵏ',
    'cat.adventure.count': '8 ⵜⵉⵔⴰⵔⵉⵏ',
    'cat.culture': 'ⵜⴰⵎⵙⵉⴷⴰⵜ ⵜⴰⴷⵍⵙⴰⵏⵜ',
    'cat.culture.count': '6 ⵉⵎⴷⴰⵏⵏ',
    'cat.sports': 'ⵜⵉⵔⴰⵔⵉⵏ ⵏ ⵓⵡⴷⵉⵡ',
    'cat.sports.count': '5 ⵜⵉⵔⴰⵔⵉⵏ',
    'cat.localProducts': 'ⵉⵎⵥⵍⴰⵢ ⵏ ⵜⴰⴷⴰⵍⵉⵜ',
    'cat.localProducts.count': 'ⵉⵎⵥⵍⴰⵢ ⵏ ⵜⵎⵏⴰⴹⵜ',
    'map.title': 'ⴰⵙⴷⵡⵓⵙ ⵏ ⴰⵣⵉⵍⴰⵍ',
    'map.desc': 'ⵜⵍⵍⴰ ⴰⵣⵉⵍⴰⵍ ⴷⴰⵔ ⵓⵡⵜⵜⵓⵏ ⵏ ⵉⵡⴷⵉⵡⵏ ⵏ ⴰⵟⵍⴰⵙ ⴰⵎⵇⵇⵔⴰⵏ, 220 ⴽⵎ ⵙ ⵓⵏⵣⵓⵍ ⴰⵙⵎⴷⴰⵢ ⵏ ⴽⴰⵢⵢⴰⴱⵍⴰⵏⴽⴰ',
    'map.f1.title': 'ⵜⴰⴷⴰⵍⵉⵜ ⵉⵜⵜⵔⵣⵢⵏ',
    'map.f1.desc': 'ⵉⵡⴷⵉⵡⵏ ⴷ ⵉⵡⴰⵍⵉⵢⵏ ⴷ ⵜⴰⵖⵍⴰⵎⵜ',
    'map.f2.title': 'ⴰⵖⵎⴰⵢ ⴰⵎⴰⵣⵉⵖ',
    'map.f2.desc': 'ⵉⵖⵔⵎⴰⵏ ⵉⵎⵓⵍⵏ ⴷ ⵜⴰⴷⵍⵙⴰ',
    'map.f3.title': 'ⴰⵏⴰⵡ ⵉⵜⵜⵓⴷⵏ',
    'map.f3.desc': 'ⵉⵜⵜⵓⵙⵏ ⵉ ⵜⵎⵙⵉⴷⴰⵜ',
    'footer.about': 'ADRAR ⵜⴳⴰ ⵜⴰⵡⵡⵓⵔⵜ ⵏⵏⴽ ⵉⴳ ⵜⵙⵏⵓⴱⵔⵛⵉⴷ ⵜⵉⵍⴰⵍ ⵏ ⵜⵖⵔⵎⵜ ⵏ ⴰⵣⵉⵍⴰⵍ ⴷ ⵜⴰⵖⵍⵉⵜ ⵜⴰⵎⴰⵣⵉⵖⵜ',
    'footer.links': 'ⵜⵉⵖⵍⴰⴼⵉⵏ',
    'footer.contact': 'ⵉⵏⵏⴰⵡⵏ ⵏ ⵜⵏⵣⵓⵜ',
    'footer.follow': 'ⵔⵥⵎⵏⴷ',
    'footer.copyright': 'ⵉⵖⵓⵔⵉⵡⵏ ⴷⵓⵔⵏ ⵉⵙⵙⴼⴽⵏ',
    'chat.title': 'ⵏⵎⵥⴰ',
    'chat.subtitle': 'ⵏⴽⵏⵉ ⵏⵏⵖ ⵏⴰⵢ ⵏⵎⵓⵏ ⴰⵏⴰⵡⵏ ⵏⵏⴽ',
    'chat.placeholder': 'ⴰⵔⴰ ⵜⴰⵏⴰⵡⵜ ⵏⵏⴽ ⴷⴰ...',
    'chat.name': 'ⵉⵙⵎ',
    'chat.email': 'ⵉⵎⴰⵢⵍ ⵏ ⵜⵔⴰⵔⴰ',
    'chat.emailRequired': 'ⵙⵙⵏ ⵉⵎⴰⵢⵍ ⴰⴷ ⵏⵣⵎⵔ ⴰⴷ ⵏⵔⴰⵔ.',
    'chat.send': 'ⴰⵣⵏ',
    'chat.welcome': 'ⴰⵣⵓⵍ! ⵎⴰⵎⴽ ⴰⵔ ⵜⵓⵙⵉⴷⵉⴷ ⴰⵏⴰⵡⵏ ⵏⵏⴽ ⵙ ⴰⵣⵉⵍⴰⵍ?',
    'chat.received': 'ⵜⴰⵏⴰⵡⵜ ⵏⵏⴽ ⵜⵜⵡⴰⵇⴱⵍ. ⵏⵔⴰ ⴰⴷ ⵏⵔⴰⵔ ⵙ ⵉⵎⴰⵢⵍ ⵏⵏⴽ ⵏⵉⵖ WhatsApp ⵎⴽ ⵉⵍⵍⴰ ⵓⵎⵇⵇⵔ ⵓⵙⵙⵏⴰⵏ.',
    'chat.sending': 'ⴰⵔ ⵜⵜⴰⵣⵏ ⵜⴰⵏⴰⵡⵜ...',
    'chat.error': 'ⵓⵔ ⵜⵣⵎⵔⵉⵖ ⴰⴷ ⵙⵙⵉⵔⵙⵖ ⵜⴰⵏⴰⵡⵜ ⵏⵏⴽ ⴰⵙⵙⴰ. ⵙⵙⵏⵖ ⵜⵉⵙⵙⵉⵏⵜ ⵏⵏⵉⴹⵏ.',
    'chat.whatsappUnavailable': 'WhatsApp ⵓⵔ ⵉⵍⵍⵉ ⴰⵙⵙⴰ.',
    'footer.newsletter': 'ⴰⵢⵙⵙⴰⵢⵢⵏ',
    'footer.newsletter.desc': 'ⵔⵥⵎ ⵉⴳ ⵜⵔⵉⴷ ⵉⵙⵙⵏⵏ ⵉⵏⵏⴰⵢⵏ',
    'footer.email': 'ⵉⵎⴰⵢⵍ ⵏⵏⴽ',
    'footer.subscribe': 'ⵔⵥⵎ',
    'nav.login': 'ⴽⴽⵛ',
    'nav.myBookings': 'ⵜⵉⵙⵙⵖⵍⵉⵡⵉⵏ ⵉⵏⵓ',
    'nav.loginOnMainSite': 'ⴰⴽⵓⵙⴰⵔ ⴳ ⵓⵙⵉⵜ ⴰⵎⵇⵇⵔⴰⵏ — ⵙⵙⵏⴷⴼ ⴷⴰ',
    'pwa.install': 'ⵙⵓⵔⵙ ⵓⵙⵙⵏⴷⵇ',
    'choice.title': 'ⴰⵏⵙⵓⴼ ⴳ ADRAR! ⵎⴰⵛ ⵜⵔⵉⴷ ⴰⴷ ⵜⵙⵡⵉⵜ?',
    'choice.guestTitle': 'ⵉⵙⵙⵖⵍ ⴰⴷ ⵙⵙⵖⵍⵖ',
    'choice.guestDesc': 'ⵣⵣⵏ ⵉⵙⵏⴷⵇⴰⵏ, ⵉⵎⵙⵙⵓⵜⵏ, ⵉⵇⵇⵇⵡⵉⵏ ⴷ ⵜⵙⵍⵍⴰⵙⵜ ⵙⵙⵖⵍ ⵎⴰ ⵉⵛⵛⴰⵢⵏ ⵉⴽ',
    'choice.ownerTitle': 'ⵓⵔⵉⵖ ⴰⵙⵏⴷⵇ / ⵜⴰⵙⵍⵍⴰⵙⵜ',
    'choice.ownerDesc': 'ⵓⵍⵉ ⴰⵙⵏⴼⵍ ⴱⴰⵛ ⴰⴷ ⵜⵎⵙⵙⵍⵉⴷ ⵜⵎⵣⵖⵉⵜ ⵏⵏⴽ',
    'choice.skip': 'ⵣⵓⵔ',
    'guest.title': 'ⵜⵉⵙⵙⵖⵍⵉⵡⵉⵏ ⵉⵏⵓ',
    'guest.subtitle': 'ⵣⵔⵉ ⴷ ⴱⴷⵍ ⵜⵉⵙⵙⵖⵍⵉⵡⵉⵏ ⵏⵏⴽ ⴷⴰ',
    'guest.empty.title': 'ⵓⵔ ⴳⵉⴳⴽ ⵢⴰⵜ ⵜⵉⵙⵙⵖⵍⵉ',
    'guest.empty.desc': 'ⴱⴰⵛ ⵜⴱⴷⵓⴷ, ⵙⵙⵖⵍ ⴰⵙⵏⴷⵇ ⵏⵖ ⵙⵙⵍⵍⵉ ⵜⴰⵙⵍⵍⴰⵙⵜ ⵙⴳ ⵓⵙⵉⵜ ⴰⴷ ⵜⴰⴼⵉⴷ ⵜⵉⵙⵙⵖⵍⵉⵡⵉⵏ ⵏⵏⴽ ⴷⴰ',
    'guest.empty.cta': 'ⵣⵔⵉ ⵉⵙⵏⴷⵇⵏ',
    'guest.status.pending': 'ⴷ ⵉⵜⵜⵔⵉⵏ',
    'guest.status.confirmed': 'ⵉⵜⵜⵓⵙⵎⵏ',
    'guest.status.cancelled': 'ⵉⵜⵜⵓⵙⵙⵉⵔ',
    'guest.status.completed': 'ⵉⵜⵜⵓⵎⴰⵎ',
    'guest.pay_pending': 'ⵓⵔ ⵉⵜⵜⵓⵅⵍⴰⵙ',
    'guest.pay_paid': 'ⵉⵜⵜⵓⵅⵍⴰⵙ',
    'guest.pay_arrival': 'ⴰⵅⵍⴰⵙ ⴳ ⵡⴰⵡⴷ',
    'guest.pay_card': 'ⵜⴰⴽⴰⵕⴷⴰ ⵏ ⵓⴱⴰⵏⴽ',
    'guest.cancel': 'ⵙⵙⵉⵔ ⵜⵉⵙⵙⵖⵍⵉ',
    'guest.cancelConfirm': 'ⵉⵙⵙ ⵜⵓⴳⵉⴷ ⴰⴷ ⵜⵙⵙⵉⵔⵉⴷ ⵜⵉⵙⵙⵖⵍⵉ ⴰⴷ? ⵓⵔ ⵉⵜⵜⵓⵣⵎⵎⵔⵏ ⴰⴷ ⵉⵔⵊⵛ',
    'guest.cancelYes': 'ⵉⵀ ⵙⵙⵉⵔⵉⵜ',
    'guest.cancelNo': 'ⵓⵀⵓ ⵃⵎⵉⴷ ⵜ',
    'guest.cancelled_msg': 'ⵜⵜⵓⵙⵙⵉⵔ ⵜⵉⵙⵙⵖⵍⵉ',
    'guest.error_cancel': 'ⵓⵔ ⵏⵖⵉⵍ ⴰⴷ ⵏⵙⵙⵉⵔ ⵜⵉⵙⵙⵖⵍⵉ, ⵛⵉⵡⵍ ⵜⵉⴽⴽⵍⵜ ⵏⵏⵉⴹⵏ',
    'guest.type_hotel': 'ⴰⵙⵏⴷⵇ',
    'guest.type_car': 'ⵜⴰⵙⵍⵍⴰⵙⵜ',
    'guest.dates': 'ⵉⵎⴰⵍⴰⵙⵏ',
    'guest.price': 'ⵙⵡⴰⵎⵎⴰ ⵏⵏⵉⵢⵏⵉ',
    'guest.guest_info': 'ⵜⴰⵏⵏⴰⵡⵜ ⵏⵏⴽ',
    'guest.notes': 'ⵜⵉⵏⴰⵡⵉⵏ',
    'guest.pay_status': 'ⵓⵙⵡⵉⵔⵔ ⵏ ⵓⵅⵍⴰⵙ',
    'guest.booking_date': 'ⴰⵙⵙ ⵏ ⵜⵉⵙⵙⵖⵍⵉ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('ar');

  const setLang = useCallback((newLang: Lang) => {
    setLangState(newLang);
    document.documentElement.lang = newLang;
    document.documentElement.dir = newLang === 'ar' || newLang === 'ber' ? 'rtl' : 'ltr';
  }, []);

  const t = useCallback(
    (key: string) => translations[lang][key] || key,
    [lang]
  );

  const isRTL = lang === 'ar' || lang === 'ber';

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
  }, [lang, isRTL]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
